version: '3'


volumes:
  postgres_data:

services:
  db:
    image: postgres:10.8
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      # https://stackoverflow.com/a/42344823
      - postgres_data:/var/lib/postgresql/data
